<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>VulCore-demo</PackageId>
    <Title>VulCore-title</Title>
    <Version>1.0.4</Version>
    <Authors>CrafterDevs</Authors>
    <Company>CrafterDevs</Company>
    <Description>Crafter Devs tarafından test için geliştirilmiştir.</Description>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>demo;crafterdevs</PackageTags>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
