name: Publish to NuGet

on:
  push:
    # tags:
    #   - 'v*.*.*'
    branches:
      - main 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Vulcore/Vulcore/Vulcore.csproj

    - name: Build
      run: dotnet build  ./Vulcore/Vulcore/Vulcore.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./Vulcore/Vulcore/Vulcore.csproj /p:IncludeReferencedProjects=true --configuration Release -o nupkg

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json